# fly.toml app configuration file generated for full-stack-open-pokedex-jlyon12 on 2024-03-27T12:22:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-jlyon12'
primary_region = 'ord'

[env]
  PORT=3000

[processes]
  app = "node app.js"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  strategy = "canary"

[[vm]]
  size = 'shared-cpu-1x'
